proyecto/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :instituciones
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "institucionese#index"
end

proyecto/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

proyecto/app/models/institucione.rb
class Institucione < ApplicationRecord
end

proyecto/app/models/regione.rb
class Regione < ApplicationRecord
end

proyecto/app/models/tipoinstitucione.rb
class Tipoinstitucione < ApplicationRecord
end

proyecto/app/models/tiporelacione.rb
class Tiporelacione < ApplicationRecord
end

proyecto/app/models/tipousuario.rb
class Tipousuario < ApplicationRecord
end

proyecto/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

proyecto/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

proyecto/app/controllers/instituciones_controller.rb
class InstitucionesController < ApplicationController
  before_action :set_institucione, only: [:show, :edit, :update, :destroy]

  # GET /instituciones
  # GET /instituciones.json
  def index
    @instituciones = Institucione.all
  end

  # GET /instituciones/1
  # GET /instituciones/1.json
  def show
  end

  # GET /instituciones/new
  def new
    @institucione = Institucione.new
  end

  # GET /instituciones/1/edit
  def edit
  end

  # POST /instituciones
  # POST /instituciones.json
  def create
    @institucione = Institucione.new(institucione_params)

    respond_to do |format|
      if @institucione.save
        format.html { redirect_to @institucione, notice: 'Institucione was successfully created.' }
        format.json { render :show, status: :created, location: @institucione }
      else
        format.html { render :new }
        format.json { render json: @institucione.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instituciones/1
  # PATCH/PUT /instituciones/1.json
  def update
    respond_to do |format|
      if @institucione.update(institucione_params)
        format.html { redirect_to @institucione, notice: 'Institucione was successfully updated.' }
        format.json { render :show, status: :ok, location: @institucione }
      else
        format.html { render :edit }
        format.json { render json: @institucione.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instituciones/1
  # DELETE /instituciones/1.json
  def destroy
    @institucione.destroy
    respond_to do |format|
      format.html { redirect_to instituciones_url, notice: 'Institucione was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institucione
      @institucione = Institucione.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institucione_params
      params.require(:institucione).permit(:nombre, :pais, :codigopostal)
    end
end

proyecto/app/helpers/application_helper.rb
module ApplicationHelper
end

proyecto/app/helpers/instituciones_helper.rb
module InstitucionesHelper
end

proyecto/app/views/instituciones/_form.html.erb
<%= form_with(model: institucione, local: true) do |form| %>
  <% if institucione.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(institucione.errors.count, "error") %> prohibited this institucione from being saved:</h2>

      <ul>
      <% institucione.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :pais %>
    <%= form.text_field :pais %>
  </div>

  <div class="field">
    <%= form.label :codigopostal %>
    <%= form.text_field :codigopostal %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

proyecto/app/views/instituciones/edit.html.erb
<h1>Editing Institucione</h1>

<%= render 'form', institucione: @institucione %>

<%= link_to 'Show', @institucione %> |
<%= link_to 'Back', instituciones_path %>

proyecto/app/views/instituciones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instituciones</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Pais</th>
      <th>Codigopostal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instituciones.each do |institucione| %>
      <tr>
        <td><%= institucione.nombre %></td>
        <td><%= institucione.pais %></td>
        <td><%= institucione.codigopostal %></td>
        <td><%= link_to 'Show', institucione %></td>
        <td><%= link_to 'Edit', edit_institucione_path(institucione) %></td>
        <td><%= link_to 'Destroy', institucione, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Institucione', new_institucione_path %>

proyecto/app/views/instituciones/new.html.erb
<h1>New Institucione</h1>

<%= render 'form', institucione: @institucione %>

<%= link_to 'Back', instituciones_path %>

proyecto/app/views/instituciones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @institucione.nombre %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @institucione.pais %>
</p>

<p>
  <strong>Codigopostal:</strong>
  <%= @institucione.codigopostal %>
</p>

<%= link_to 'Edit', edit_institucione_path(@institucione) %> |
<%= link_to 'Back', instituciones_path %>

proyecto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>